### ISSUE TITLE
questions about xjoin

### ISSUE THREAD

**Issue by zjin-lcf** [Eug9/XJoin#1]
I have some questions about xjoin. Do you print the results for verification ? Is there a reference to the CUDA version which may help verification ?  

Thanks

**Comment by Eug9** [comment]
Hello, the link to the CUDA version is: https://github.com/anilshanbhag/crystal. 
As in the CUDA version, we print only the total number of tuples resulting after the join operation, and in all our experiments  these numbers match exactly.
